# Generated by Django 2.0.2 on 2018-09-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
